language: ruby
rvm:
  - 2.1.5
bundler_args: --without production
before_script: mysql -e 'create database hardcover_test'
script:
  - RAILS_ENV=test bundle exec rake db:migrate test
  - bundle exec rake spec
